# Saving the Final Data Set

First, install the required Python libraries if not done already. See
[Installing Required Python Libraries](../00_Installing_Required_Python_Libraries.md).

If you're new to Python, you might be interested in [Introduction to Python Lists and Dictionaries for Data Science](../01_Introduction_to_Python_Data_Types.md).

Begin by importing the required packages.

In [1]:
import pandas as pd

## Run the data access notebooks

In [2]:
%run '../03_01_Accessing_and_Exploring_Data/01_Accessing_and_Reading_Local_Files.ipynb'
%run '../03_01_Accessing_and_Exploring_Data/02_Accessing_and_Reading_Data_Lake_Files.ipynb'
%run '../03_01_Accessing_and_Exploring_Data/03_Accessing_and_Reading_Database-Data_Lakehouse_Data.ipynb'

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customerSubscrCode  3 non-null      int64
 1   customerSubscrStat  3 non-null      object
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      5000 non-null   float64
 1   LostCustomer            5000 non-null   float64
 2   regionPctCustomers      5000 non-null   float64
 3   numOfTotalReturns       5000 non-null   float64
 4   wksSinceLastPurch       5000 non-null   float64
 5   basktPurchCount12Month  5000 non-null   float64
 6   LastPurchaseAmount      5000 non-null   float64
 7   AvgPurchaseAmount12     5000 non-null   float64
 8   AvgPurchaseAmountTotal  5000 non-null   float64
 9   intAdExposureCount12    5000 non-null   float64
 10  intAdExposureCount36    5000 non-null   float64
 11  intAdExposureCountAll   5000 non-null   float64
 12  socialMediaAdCount12    5000 non-null   float64
 13  socialMediaAdCount36    5000 non-null   float64
 14  socialMediaAdCountAll   5000 non-null   float64
 15  totalNumProdPurchased   5000 non-null   float64
 16  custInitiatedContacts   5000 non-null   float64
 17  avgDiscountValue12      3618 non-null   float64
 18  customersales           5000 non-null   float64
 19  wksSinceFirstPurch      5000 non-null   float64
 20  reviewId                782 non-null    float64
 21  custId                  5000 non-null   float64
dtypes: float64(22)
memory usage: 859.5 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4998 entries, 0 to 4997
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   custId              4998 non-null   float64
 1   DemHomeOwnerCode    4998 non-null   object
 2   customerGender      4998 non-null   object
 3   EstimatedIncome     4998 non-null   float64
 4   regionMedHomeVal    4998 non-null   float64
 5   customerSubscrCode  4998 non-null   float64
 6   birthDate           3741 non-null   datetime64[s]
dtypes: datetime64[s](1), float64(4), object(2)
memory usage: 273.5+ KB

## Run the data joining notebook

In [3]:
%run './01_Combining_Data.ipynb'

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customerSubscrCode  3 non-null      int64
 1   customerSubscrStat  3 non-null      object
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      5000 non-null   float64
 1   LostCustomer            5000 non-null   float64
 2   regionPctCustomers      5000 non-null   float64
 3   numOfTotalReturns       5000 non-null   float64
 4   wksSinceLastPurch       5000 non-null   float64
 5   basktPurchCount12Month  5000 non-null   float64
 6   LastPurchaseAmount      5000 non-null   float64
 7   AvgPurchaseAmount12     5000 non-null   float64
 8   AvgPurchaseAmountTotal  5000 non-null   float64
 9   intAdExposureCount12    5000 non-null   float64
 10  intAdExposureCount36    5000 non-null   float64
 11  intAdExposureCountAll   5000 non-null   float64
 12  socialMediaAdCount12    5000 non-null   float64
 13  socialMediaAdCount36    5000 non-null   float64
 14  socialMediaAdCountAll   5000 non-null   float64
 15  totalNumProdPurchased   5000 non-null   float64
 16  custInitiatedContacts   5000 non-null   float64
 17  avgDiscountValue12      3618 non-null   float64
 18  customersales           5000 non-null   float64
 19  wksSinceFirstPurch      5000 non-null   float64
 20  reviewId                782 non-null    float64
 21  custId                  5000 non-null   float64
dtypes: float64(22)
memory usage: 859.5 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4998 entries, 0 to 4997
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   custId              4998 non-null   float64
 1   DemHomeOwnerCode    4998 non-null   object
 2   customerGender      4998 non-null   object
 3   EstimatedIncome     4998 non-null   float64
 4   regionMedHomeVal    4998 non-null   float64
 5   customerSubscrCode  4998 non-null   float64
 6   birthDate           3741 non-null   datetime64[s]
dtypes: datetime64[s](1), float64(4), object(2)
memory usage: 273.5+ KB

## Run the data transformation notebook

In [4]:
%run './02_Transforming_and_Enriching_Data.ipynb'

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customerSubscrCode  3 non-null      int64
 1   customerSubscrStat  3 non-null      object
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      5000 non-null   float64
 1   LostCustomer            5000 non-null   float64
 2   regionPctCustomers      5000 non-null   float64
 3   numOfTotalReturns       5000 non-null   float64
 4   wksSinceLastPurch       5000 non-null   float64
 5   basktPurchCount12Month  5000 non-null   float64
 6   LastPurchaseAmount      5000 non-null   float64
 7   AvgPurchaseAmount12     5000 non-null   float64
 8   AvgPurchaseAmountTotal  5000 non-null   float64
 9   intAdExposureCount12    5000 non-null   float64
 10  intAdExposureCount36    5000 non-null   float64
 11  intAdExposureCountAll   5000 non-null   float64
 12  socialMediaAdCount12    5000 non-null   float64
 13  socialMediaAdCount36    5000 non-null   float64
 14  socialMediaAdCountAll   5000 non-null   float64
 15  totalNumProdPurchased   5000 non-null   float64
 16  custInitiatedContacts   5000 non-null   float64
 17  avgDiscountValue12      3618 non-null   float64
 18  customersales           5000 non-null   float64
 19  wksSinceFirstPurch      5000 non-null   float64
 20  reviewId                782 non-null    float64
 21  custId                  5000 non-null   float64
dtypes: float64(22)
memory usage: 859.5 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4998 entries, 0 to 4997
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   custId              4998 non-null   float64
 1   DemHomeOwnerCode    4998 non-null   object
 2   customerGender      4998 non-null   object
 3   EstimatedIncome     4998 non-null   float64
 4   regionMedHomeVal    4998 non-null   float64
 5   customerSubscrCode  4998 non-null   float64
 6   birthDate           3741 non-null   datetime64[s]
dtypes: datetime64[s](1), float64(4), object(2)
memory usage: 273.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customerSubscrCode  3 non-null      int64
 1   customerSubscrStat  3 non-null      object
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      5000 non-null   float64
 1   LostCustomer            5000 non-null   float64
 2   regionPctCustomers      5000 non-null   float64
 3   numOfTotalReturns       5000 non-null   float64
 4   wksSinceLastPurch       5000 non-null   float64
 5   basktPurchCount12Month  5000 non-null   float64
 6   LastPurchaseAmount      5000 non-null   float64
 7   AvgPurchaseAmount12     5000 non-null   float64
 8   AvgPurchaseAmountTotal  5000 non-null   float64
 9   intAdExposureCount12    5000 non-null   float64
 10  intAdExposureCount36    5000 non-null   float64
 11  intAdExposureCountAll   5000 non-null   float64
 12  socialMediaAdCount12    5000 non-null   float64
 13  socialMediaAdCount36    5000 non-null   float64
 14  socialMediaAdCountAll   5000 non-null   float64
 15  totalNumProdPurchased   5000 non-null   float64
 16  custInitiatedContacts   5000 non-null   float64
 17  avgDiscountValue12      3618 non-null   float64
 18  customersales           5000 non-null   float64
 19  wksSinceFirstPurch      5000 non-null   float64
 20  reviewId                782 non-null    float64
 21  custId                  5000 non-null   float64
dtypes: float64(22)
memory usage: 859.5 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4998 entries, 0 to 4997
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   custId              4998 non-null   float64
 1   DemHomeOwnerCode    4998 non-null   object
 2   customerGender      4998 non-null   object
 3   EstimatedIncome     4998 non-null   float64
 4   regionMedHomeVal    4998 non-null   float64
 5   customerSubscrCode  4998 non-null   float64
 6   birthDate           3741 non-null   datetime64[s]
dtypes: datetime64[s](1), float64(4), object(2)
memory usage: 273.5+ KB

## Save as a CSV file

In [5]:
df.to_csv('../../data/output/customer_churn_abt.csv', index=False)

## Export to Snowflake (if applicable)

If we had Snowflake and wanted to save a table in it, we would use the following code.

```python
import snowflake as sf
import snowflake.connector
import json
from snowflake.connector.pandas_tools import write_pandas

sf_credential = '../../keys/snowflake_cred.json'

with open(sf_credential, "r") as f:
    sf_credentials_dict = json.load(f)

conn = sf.connector.connect(**sf_credentials_dict)

success, nchunks, nrows, output = write_pandas(
    conn=conn,
    df=df,
    table_name="customer_churn_abt",
    auto_create_table=True,
    overwrite=True
)

conn.close()
```

## Export to Google Cloud Storage (if applicable)

If we had GCS and wanted to save a table in it as a Parquet data set, we would use the following code.

```python
import json

gcs_key = '../../keys/gel-sas1-writer.json'

bucket_name = 'sas1-learn'

output_filename = 'customer_churn_abt.parquet'

output_path = f'gcs://{bucket_name}/data/{output_filename}'

df.to_parquet(
    output_path,
    engine='pyarrow',
    storage_options={'token': gcs_key}
)

print(f"DataFrame written to {output_path}")
```